name: Compile with CMAKE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Copy repository
      uses: actions/checkout@v4

    - name: Download 
      uses: actions/checkout@v4
      with:
        repository: crosire/reshade
        path: reshade_source

    - name: Configure CMAKE
      run: |
        mkdir build
        cd build
        cmake .. -A x64 -DRESHADE_INCLUDE_DIR="../reshade_source/include"
        cmake --build . --config Release

    - name: Artefact
      uses: actions/upload-artifact@v4
      with:
        name: MagpieReshadeInput-DLL
        path: build/Release/*.dll
