name: Compilar com CMake

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Copiar repositório
      uses: actions/checkout@v4

    - name: Baixar headers do ReShade
      uses: actions/checkout@v4
      with:
        repository: crosire/reshade
        path: reshade_source

    - name: Configurar CMake e Build
      run: |
        mkdir build
        cd build
        cmake .. -A x64 -DRESHADE_INCLUDE_DIR="$env:GITHUB_WORKSPACE/reshade_source/include"
        cmake --build . --config Release

    - name: Salvar a DLL gerada (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: MagpieReshadeInput-DLL
        path: build/Release/*.dll
